# Generated by Django 5.2 on 2025-04-24 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contracts", "0001_initial"),
        ("customers", "0001_initial"),
        ("products", "0002_remove_product_price_product_cost"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customer_contracts",
                to="customers.customer",
                verbose_name="Клиент",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="manager",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="manager_contracts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Менеджер",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_contracts",
                to="products.product",
                verbose_name="Услуга",
            ),
        ),
    ]
